### ISSUE TITLE
Tx Calibration: Frequency out of range, available range: 2.5-120 MHz

### ISSUE THREAD

**Issue by vsboost** [emvivre/limesdr_toolbox#3]
I'm getting this all the time, anything i can do to stop it?

**Comment by emvivre** [comment]
Thank your for your review.

It turns out that the calibrate bandwidth must be in the range [2.5 - 120] MHz. I fix the default calibrate bandwidth to 8Mhz, and the warning message is no more displayed. In the limesdr_toolbox, you can set the calibrate bandwidth with the -b parameter if you want to experiment others values.

Have a nice day :)
